# Generated by Django 2.1.3 on 2018-11-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='attending',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='holy_metromony',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='wedding_party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
