# Generated by Django 2.1.3 on 2018-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20181110_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='holy_metromony',
            field=models.CharField(choices=[('Attending', 'Attending'), ('Not Attending', 'Not Attending'), ('Mybe', 'Mybe')], default='Attending', max_length=100),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='wedding_party',
            field=models.CharField(choices=[('Attending', 'Attending'), ('Not Attending', 'Not Attending'), ('Mybe', 'Mybe')], default='Attending', max_length=100),
        ),
    ]
